# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.hostname = "hundoword"
  config.vm.box = "hashicorp/precise64"
  config.vm.define "hundoword" do |hundoword|
  end

  # ASCII - H = 72 W = 87
  config.vm.network "private_network", ip: "192.168.72.87"

  # Settings for low resources and networking (so DNS works right)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.synced_folder "../../src", "/home/vagrant/src"

  config.vm.provision "shell", path: "provision.sh"

end
