# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "digital_ocean"
  config.vm.hostname = 'demo.hundoword.com'

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/do_vagrant_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.token = ENV.fetch('DIGITALOCEAN_ACCESS_TOKEN', '')
    provider.image = 3240036
    provider.region = "nyc3"
    provider.size = '512mb'
  end

  config.vm.synced_folder "../../src", "/home/vagrant/src"

  config.vm.provision "shell", path: "provision.sh"

end
